# Generated by Django 3.2 on 2022-09-15 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0003_tokenproxy'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('accounts', '0002_demomodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DemoModel',
        ),
    ]
